version: '3.7'
services:
  server:
    image: mitwilsch/toto/server
    build:
      context: ./
      dockerfile: Dockerfile-server
    ports:
      - '8080:8080'
    links:
      - mongodb
  mongodb:
    image: mongo
